#/**************************************************************
# * Team:      Elon Tusk Calculator
# *
# * Authors:   Peter Zdravecký <xzdrav00@vutbr.cz>
# *            Eduard Frlička  <xzdrav00@vutbr.cz>
# *            Jakub Vaňo      <xvano00@vutbr.cz>
# *            Daniel Fajmon   <xfajmo05@vutbr.cz>
# **************************************************************/

.PHONY: all pack clean run profile help

all:
pack:
clean:
run:
    if not exist "$(PROJ)" make build
	    $(PROJ)
profile:
help: